# Generated by Django 4.1.5 on 2023-05-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_patinete_usuario_remove_profile_usuario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puestocarga',
            old_name='nombre',
            new_name='estacion',
        ),
        migrations.AlterField(
            model_name='puestocarga',
            name='numeroPuesto',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
