# Generated by Django 4.1.5 on 2023-06-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_profile_patinete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patinete',
            name='identificador',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
