# Generated by Django 4.1.5 on 2023-06-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_patinete_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patinete',
            name='precio_minuto',
        ),
        migrations.AlterField(
            model_name='patinete',
            name='precio_desbloqueo',
            field=models.DecimalField(decimal_places=2, default=1, editable=False, max_digits=10),
        ),
    ]
