# Generated by Django 4.1.5 on 2023-05-04 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('nombre', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=100)),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Patinete',
            fields=[
                ('identificador', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('vatios', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.BooleanField()),
                ('precio_minuto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_desbloqueo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PuestoCarga',
            fields=[
                ('numeroPuesto', models.DecimalField(decimal_places=2, max_digits=10, primary_key=True, serialize=False)),
                ('disponible', models.BooleanField()),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.estacion')),
            ],
        ),
        migrations.CreateModel(
            name='Registros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desbloqueo', models.DateTimeField()),
                ('fecha_entrega', models.DateTimeField(null=True)),
                ('coste_final', models.FloatField(null=True)),
                ('identificador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patinete')),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.estacion')),
                ('numeroPuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.puestocarga')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=9)),
                ('telefono', models.IntegerField(null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
