# Generated by Django 4.1.5 on 2023-05-25 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_puestocarga_estacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puestocarga',
            name='estacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.estacion'),
        ),
        migrations.AlterField(
            model_name='puestocarga',
            name='numeroPuesto',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
