# Generated by Django 4.1.5 on 2023-06-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_puestocarga_estacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='puestocarga',
            name='puesto',
            field=models.IntegerField(default=1),
        ),
    ]
