# Generated by Django 4.1.5 on 2023-06-12 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_profile_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='patinete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.patinete'),
        ),
    ]
