# Generated by Django 4.1.5 on 2023-06-12 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_patinete_identificador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patinete',
            name='estado',
        ),
    ]
