# Generated by Django 4.1.5 on 2023-06-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_profile_patinete_profile_patinetes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='patinetes',
            field=models.ManyToManyField(blank=True, to='main.patinete'),
        ),
    ]
