# Generated by Django 4.1.5 on 2023-06-19 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0020_alter_patinete_propietario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registros',
            name='coste_final',
        ),
        migrations.RemoveField(
            model_name='registros',
            name='fecha_entrega',
        ),
        migrations.RemoveField(
            model_name='registros',
            name='identificador',
        ),
        migrations.RemoveField(
            model_name='registros',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='registros',
            name='numeroPuesto',
        ),
        migrations.AddField(
            model_name='registros',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historial', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='puestocarga',
            name='estacion',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.estacion'),
        ),
        migrations.AlterField(
            model_name='puestocarga',
            name='numeroPuesto',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='registros',
            name='fecha_desbloqueo',
            field=models.DateTimeField(null=True),
        ),
    ]
