# Generated by Django 4.1.5 on 2023-05-25 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppUser',
        ),
    ]
